workspace(name = "tink_objc")

local_repository(
    name = "tink_cc",
    path = "../cc",
)

load("@tink_cc//:tink_cc_deps.bzl", "tink_cc_deps")
tink_cc_deps()

load("@tink_cc//:tink_cc_deps_init.bzl", "tink_cc_deps_init")
tink_cc_deps_init()

load("@tink_objc//:tink_objc_deps.bzl", "tink_objc_deps")
tink_objc_deps()

load("@tink_objc//:tink_objc_deps_init.bzl", "tink_objc_deps_init")
tink_objc_deps_init()
