workspace(name = "examples_cc")

# The local_repository() rule is used below because the workspaces referenced
# are all located within the Tink git repository.
#
# To replicate this setup in a workspace located in a separate repository, you
# can:
#
# 1. Load the http_archive() rule by using:
#
# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
#
# 2. Use the equivalent, commented-out http_archive() rules below as a starting
#    point.
#
# See the Tink C++ HOW-TO for more details:
#   https://github.com/google/tink/blob/master/docs/CPP-HOWTO.md


local_repository(
    name = "tink_cc",
    path = "../../cc",
)
# http_archive(
#     name = "tink_cc",
#     urls = ["https://github.com/google/tink/archive/master.zip"],
#     strip_prefix = "tink-master/cc",
# )


# Load Tink dependencies.

load("@tink_cc//:tink_cc_deps.bzl", "tink_cc_deps")
tink_cc_deps()

load("@tink_cc//:tink_cc_deps_init.bzl", "tink_cc_deps_init")
tink_cc_deps_init()
