workspace(name = "tink_java_examples")

# The local_repository() rule is used below because the workspaces referenced
# are all located within the Tink git repository.
#
# To replicate this setup in a workspace located in a separate repository, you
# can:
#
# 1. Load the http_archive() rule by using:
#
# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
#
# 2. Use the equivalent, commented-out http_archive() rules below as a starting
#    point.
#
# See the Tink Java HOW-TO for more details:
#   https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md

local_repository(
    name = "tink_java",
    path = "../",
)
# http_archive(
#     name = "tink_java",
#     urls = ["https://github.com/google/tink/archive/master.zip"],
#     strip_prefix = "tink-master/java_src",
# )

# Load Tink dependencies.

load("@tink_java//:tink_java_deps.bzl", "tink_java_deps", "TINK_MAVEN_ARTIFACTS")

tink_java_deps()

load("@tink_java//:tink_java_deps_init.bzl", "tink_java_deps_init")

tink_java_deps_init()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = TINK_MAVEN_ARTIFACTS + [
      "args4j:args4j:2.33",
      "com.google.cloud:google-cloud-storage:2.3.0",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
