// Copyright 2017 Google Inc.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//      http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
////////////////////////////////////////////////////////////////////////////////

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hmac.proto

package hmac_go_proto // import "github.com/google/tink/proto/hmac_go_proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common_go_proto "github.com/google/tink/proto/common_go_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HmacParams struct {
	Hash                 common_go_proto.HashType `protobuf:"varint,1,opt,name=hash,proto3,enum=google.crypto.tink.HashType" json:"hash,omitempty"`
	TagSize              uint32                   `protobuf:"varint,2,opt,name=tag_size,json=tagSize,proto3" json:"tag_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *HmacParams) Reset()         { *m = HmacParams{} }
func (m *HmacParams) String() string { return proto.CompactTextString(m) }
func (*HmacParams) ProtoMessage()    {}
func (*HmacParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f08b5807c357b029, []int{0}
}
func (m *HmacParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HmacParams.Unmarshal(m, b)
}
func (m *HmacParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HmacParams.Marshal(b, m, deterministic)
}
func (dst *HmacParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HmacParams.Merge(dst, src)
}
func (m *HmacParams) XXX_Size() int {
	return xxx_messageInfo_HmacParams.Size(m)
}
func (m *HmacParams) XXX_DiscardUnknown() {
	xxx_messageInfo_HmacParams.DiscardUnknown(m)
}

var xxx_messageInfo_HmacParams proto.InternalMessageInfo

func (m *HmacParams) GetHash() common_go_proto.HashType {
	if m != nil {
		return m.Hash
	}
	return common_go_proto.HashType_UNKNOWN_HASH
}

func (m *HmacParams) GetTagSize() uint32 {
	if m != nil {
		return m.TagSize
	}
	return 0
}

// key_type: type.googleapis.com/google.crypto.tink.HmacKey
type HmacKey struct {
	Version              uint32      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Params               *HmacParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	KeyValue             []byte      `protobuf:"bytes,3,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HmacKey) Reset()         { *m = HmacKey{} }
func (m *HmacKey) String() string { return proto.CompactTextString(m) }
func (*HmacKey) ProtoMessage()    {}
func (*HmacKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f08b5807c357b029, []int{1}
}
func (m *HmacKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HmacKey.Unmarshal(m, b)
}
func (m *HmacKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HmacKey.Marshal(b, m, deterministic)
}
func (dst *HmacKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HmacKey.Merge(dst, src)
}
func (m *HmacKey) XXX_Size() int {
	return xxx_messageInfo_HmacKey.Size(m)
}
func (m *HmacKey) XXX_DiscardUnknown() {
	xxx_messageInfo_HmacKey.DiscardUnknown(m)
}

var xxx_messageInfo_HmacKey proto.InternalMessageInfo

func (m *HmacKey) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *HmacKey) GetParams() *HmacParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *HmacKey) GetKeyValue() []byte {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type HmacKeyFormat struct {
	Params               *HmacParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	KeySize              uint32      `protobuf:"varint,2,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HmacKeyFormat) Reset()         { *m = HmacKeyFormat{} }
func (m *HmacKeyFormat) String() string { return proto.CompactTextString(m) }
func (*HmacKeyFormat) ProtoMessage()    {}
func (*HmacKeyFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_f08b5807c357b029, []int{2}
}
func (m *HmacKeyFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HmacKeyFormat.Unmarshal(m, b)
}
func (m *HmacKeyFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HmacKeyFormat.Marshal(b, m, deterministic)
}
func (dst *HmacKeyFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HmacKeyFormat.Merge(dst, src)
}
func (m *HmacKeyFormat) XXX_Size() int {
	return xxx_messageInfo_HmacKeyFormat.Size(m)
}
func (m *HmacKeyFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_HmacKeyFormat.DiscardUnknown(m)
}

var xxx_messageInfo_HmacKeyFormat proto.InternalMessageInfo

func (m *HmacKeyFormat) GetParams() *HmacParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *HmacKeyFormat) GetKeySize() uint32 {
	if m != nil {
		return m.KeySize
	}
	return 0
}

func init() {
	proto.RegisterType((*HmacParams)(nil), "google.crypto.tink.HmacParams")
	proto.RegisterType((*HmacKey)(nil), "google.crypto.tink.HmacKey")
	proto.RegisterType((*HmacKeyFormat)(nil), "google.crypto.tink.HmacKeyFormat")
}

func init() { proto.RegisterFile("proto/hmac.proto", fileDescriptor_f08b5807c357b029) }

var fileDescriptor_f08b5807c357b029 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xc9, 0x94, 0x6d, 0xbe, 0x3a, 0x91, 0x9c, 0x3a, 0x1d, 0x32, 0x76, 0x2a, 0x1e, 0x52,
	0x99, 0xe0, 0x07, 0xd8, 0x41, 0x26, 0x03, 0x29, 0x75, 0x0a, 0x7a, 0x29, 0x69, 0x08, 0x69, 0xe9,
	0xd2, 0xb7, 0xb4, 0xd9, 0x30, 0xfb, 0x38, 0x7e, 0x52, 0x69, 0x3a, 0xff, 0xe1, 0x2e, 0xde, 0xf2,
	0x90, 0x27, 0xbf, 0x5f, 0xde, 0x04, 0xce, 0xca, 0x0a, 0x0d, 0x06, 0xa9, 0xe6, 0x82, 0xb9, 0x25,
	0xa5, 0x0a, 0x51, 0xad, 0x24, 0x13, 0x95, 0x2d, 0x0d, 0x32, 0x93, 0x15, 0xf9, 0x39, 0x6d, 0x5b,
	0x02, 0xb5, 0xc6, 0xa2, 0xed, 0x4d, 0x5e, 0x00, 0xe6, 0x9a, 0x8b, 0x90, 0x57, 0x5c, 0xd7, 0xf4,
	0x1a, 0x0e, 0x53, 0x5e, 0xa7, 0x1e, 0x19, 0x13, 0xff, 0x74, 0x3a, 0x62, 0x7f, 0x21, 0x6c, 0xce,
	0xeb, 0x74, 0x69, 0x4b, 0x19, 0xb9, 0x26, 0x1d, 0x42, 0xdf, 0x70, 0x15, 0xd7, 0xd9, 0x56, 0x7a,
	0x9d, 0x31, 0xf1, 0x07, 0x51, 0xcf, 0x70, 0xf5, 0x98, 0x6d, 0xe5, 0xe4, 0x0d, 0x7a, 0x0d, 0x7a,
	0x21, 0x2d, 0xf5, 0xa0, 0xb7, 0x91, 0x55, 0x9d, 0x61, 0xe1, 0xd0, 0x83, 0xe8, 0x33, 0xd2, 0x5b,
	0xe8, 0x96, 0xce, 0xed, 0x4e, 0x1f, 0x4f, 0x2f, 0xf7, 0x3a, 0xbf, 0x6e, 0x18, 0xed, 0xda, 0xf4,
	0x02, 0x8e, 0x72, 0x69, 0xe3, 0x0d, 0x5f, 0xad, 0xa5, 0x77, 0x30, 0x26, 0xfe, 0x49, 0xd4, 0xcf,
	0xa5, 0x7d, 0x6e, 0xf2, 0x24, 0x81, 0xc1, 0xce, 0x7c, 0x87, 0x95, 0xe6, 0xe6, 0x87, 0x85, 0xfc,
	0xcb, 0x32, 0x84, 0x06, 0xfa, 0x6b, 0xba, 0x5c, 0xda, 0x66, 0xba, 0xd9, 0x13, 0x8c, 0x04, 0xea,
	0x7d, 0x1c, 0xf7, 0xb0, 0x21, 0x79, 0xbd, 0x52, 0x99, 0x49, 0xd7, 0x09, 0x13, 0xa8, 0x83, 0xb6,
	0x16, 0x34, 0xfb, 0xc1, 0xf7, 0x5f, 0xc5, 0x0a, 0x63, 0x97, 0xde, 0x3b, 0xdd, 0xe5, 0xfd, 0xc3,
	0x22, 0x9c, 0x25, 0x5d, 0x97, 0x6f, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xca, 0x97, 0x20, 0x24,
	0xd2, 0x01, 0x00, 0x00,
}
