workspace(name = "tink_cc_awskms")

# TODO(ambrosin): Use http_archive when the necessary changes are in GitHub.
#
# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
#
# http_archive(
#     name = "tink_base",
#     strip_prefix = "tink-master/",
#     urls = ["https://github.com/google/tink/archive/master.zip"],
# )
#
# http_archive(
#     name = "tink_cc",
#     strip_prefix = "tink-master/cc",
#     urls = ["https://github.com/google/tink/archive/master.zip"],
# )

local_repository(
    name = "tink_base",
    path = "../../..",
)

local_repository(
    name = "tink_cc",
    path = "../../../cc",
)

# Load Tink dependencies.

load("@tink_base//:tink_base_deps.bzl", "tink_base_deps")

tink_base_deps()

load("@tink_base//:tink_base_deps_init.bzl", "tink_base_deps_init")

tink_base_deps_init()

load("@tink_cc//:tink_cc_deps.bzl", "tink_cc_deps")

tink_cc_deps()

load("@tink_cc//:tink_cc_deps_init.bzl", "tink_cc_deps_init")

tink_cc_deps_init()

load("@tink_cc_awskms//:tink_cc_awskms_deps.bzl", "tink_cc_awskms_deps")

tink_cc_awskms_deps()
