package com.google.k2crypto;

/**
 * TODO: Insert description here. (generated by maheswaran)
 */
public class SecuredData {

  // get data
  // decrypt if encrypted and then return data
  // verify signature if provided
  // verify HMAC if provided
  // throw exceptions if any of these fail
  // takes a compound key and uses it to do all this
}
