licenses(["notice"])  # Apache 2.0

package(
    default_visibility = ["//visibility:public"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

# Mac interface
go_library(
    name = "mac_interface",
    srcs = ["mac.go"],
)
