workspace(name = "tink_go")

local_repository(
    name = "tink_base",
    path = "..",
)

load("@tink_base//:tink_base_deps.bzl", "tink_base_deps")
tink_base_deps()

load("@tink_base//:tink_base_deps_init.bzl", "tink_base_deps_init")
tink_base_deps_init()

load("@tink_go//:tink_go_deps.bzl", "tink_go_deps")
tink_go_deps()

load("@tink_go//:tink_go_deps_init.bzl", "tink_go_deps_init")
tink_go_deps_init()

# TODO(b/213404399): Remove after Gazelle issue is fixed.
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
gazelle_dependencies()
go_repository(
    name = "com_google_cloud_go_compute",
    importpath = "cloud.google.com/go/compute",
    sum = "h1:rSUBvAyVwNJ5uQCKNJFMwPtTvJkfN38b6Pvb9zZoqJ8=",
    version = "v0.1.0",
)
