licenses(["notice"])  # Apache 2.0

filegroup(
    name = "hybrid",
    srcs = glob(["hybrid/*.ascii"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "aead",
    srcs = glob(["aead/*.ascii"]),
    visibility = ["//visibility:public"],
)
