# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Tink'

  # Pods for swiftExample

  target 'swiftExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
