licenses(["notice"])

cc_library(
    name = "gmock",
    testonly = 1,
    srcs = [
        "googlemock/include/gmock/internal/custom/gmock-generated-actions.h",
        "googlemock/include/gmock/internal/custom/gmock-matchers.h",
        "googlemock/include/gmock/internal/custom/gmock-port.h",
        "googlemock/include/gmock/internal/gmock-generated-internal-utils.h",
        "googlemock/include/gmock/internal/gmock-internal-utils.h",
        "googlemock/include/gmock/internal/gmock-port.h",
        "googlemock/src/gmock.cc",
        "googlemock/src/gmock-cardinalities.cc",
        "googlemock/src/gmock-internal-utils.cc",
        "googlemock/src/gmock-matchers.cc",
        "googlemock/src/gmock-spec-builders.cc",
    ],
    hdrs = [
        "googlemock/include/gmock/gmock.h",
        "googlemock/include/gmock/gmock-actions.h",
        "googlemock/include/gmock/gmock-cardinalities.h",
        "googlemock/include/gmock/gmock-generated-actions.h",
        "googlemock/include/gmock/gmock-generated-function-mockers.h",
        "googlemock/include/gmock/gmock-generated-matchers.h",
        "googlemock/include/gmock/gmock-generated-nice-strict.h",
        "googlemock/include/gmock/gmock-matchers.h",
        "googlemock/include/gmock/gmock-more-actions.h",
        "googlemock/include/gmock/gmock-more-matchers.h",
        "googlemock/include/gmock/gmock-spec-builders.h",
    ],
    includes = [
        "./googlemock/include",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":gtest",
    ],
)

cc_library(
    name = "gtest",
    testonly = 1,
    srcs = [
        "googletest/include/gtest/internal/custom/gtest.h",
        "googletest/include/gtest/internal/custom/gtest-port.h",
        "googletest/include/gtest/internal/custom/gtest-printers.h",
        "googletest/include/gtest/internal/gtest-death-test-internal.h",
        "googletest/include/gtest/internal/gtest-filepath.h",
        "googletest/include/gtest/internal/gtest-internal.h",
        "googletest/include/gtest/internal/gtest-linked_ptr.h",
        "googletest/include/gtest/internal/gtest-param-util.h",
        "googletest/include/gtest/internal/gtest-param-util-generated.h",
        "googletest/include/gtest/internal/gtest-port.h",
        "googletest/include/gtest/internal/gtest-port-arch.h",
        "googletest/include/gtest/internal/gtest-string.h",
        "googletest/include/gtest/internal/gtest-tuple.h",
        "googletest/include/gtest/internal/gtest-type-util.h",
        "googletest/src/gtest.cc",
        "googletest/src/gtest-death-test.cc",
        "googletest/src/gtest-filepath.cc",
        "googletest/src/gtest-internal-inl.h",
        "googletest/src/gtest-port.cc",
        "googletest/src/gtest-printers.cc",
        "googletest/src/gtest-test-part.cc",
        "googletest/src/gtest-typed-test.cc",
    ],
    hdrs = [
        "googletest/include/gtest/gtest.h",
        "googletest/include/gtest/gtest-death-test.h",
        "googletest/include/gtest/gtest-message.h",
        "googletest/include/gtest/gtest-param-test.h",
        "googletest/include/gtest/gtest-printers.h",
        "googletest/include/gtest/gtest-spi.h",
        "googletest/include/gtest/gtest-test-part.h",
        "googletest/include/gtest/gtest-typed-test.h",
        "googletest/include/gtest/gtest_pred_impl.h",
        "googletest/include/gtest/gtest_prod.h",
    ],
    includes = [
        "./googletest",
        "./googletest/include",
    ],
    linkopts = ["-lpthread"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "gtest_main",
    testonly = 1,
    srcs = ["googletest/src/gtest_main.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":gmock",
        ":gtest",
    ],
)
