workspace(name = "tools")

local_repository(
    name = "tink_base",
    path = "..",
)

local_repository(
    name = "tink_cc",
    path = "../cc",
)

local_repository(
    name = "tink_java",
    path = "../java_src",
)

local_repository(
    name = "tink_go",
    path = "../go",
)

local_repository(
    name = "tink_py",
    path = "../python",
)

load("@tink_py//:tink_py_deps.bzl", "tink_py_deps")
tink_py_deps()

load("@tink_py//:tink_py_deps_init.bzl", "tink_py_deps_init")
tink_py_deps_init("tink_py")

load("@rules_python//python:pip.bzl", "pip_install")
pip_install(
   name = "pip_deps",
   requirements = "//:requirements.txt",
)

load("@tink_base//:tink_base_deps.bzl", "tink_base_deps")
tink_base_deps()

load("@tink_base//:tink_base_deps_init.bzl", "tink_base_deps_init")
tink_base_deps_init()

load("@tink_cc//:tink_cc_deps.bzl", "tink_cc_deps")
tink_cc_deps()

load("@tink_cc//:tink_cc_deps_init.bzl", "tink_cc_deps_init")
tink_cc_deps_init()

load("@tink_java//:tink_java_deps.bzl", "tink_java_deps")
tink_java_deps()

load("@tink_java//:tink_java_deps_init.bzl", "tink_java_deps_init")
tink_java_deps_init()

load("@tink_go//:tink_go_deps.bzl", "tink_go_deps")
tink_go_deps()

load("@tink_go//:tink_go_deps_init.bzl", "tink_go_deps_init")
tink_go_deps_init()

# TODO(b/213404399): Remove after Gazelle issue is fixed.
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
gazelle_dependencies()
go_repository(
    name = "com_google_cloud_go_compute",
    importpath = "cloud.google.com/go/compute",
    sum = "h1:rSUBvAyVwNJ5uQCKNJFMwPtTvJkfN38b6Pvb9zZoqJ8=",
    version = "v0.1.0",
)
